sudo: false
cache:
  - apt

matrix:
  include:
    - env: GCC_VERSION=4.9
      language: cpp
      addons: &gcc49
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - valgrind
    - env: GCC_VERSION=5
      language: cpp
      addons: &gcc5
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - valgrind

before_install:
  - |
    if [ -n "$GCC_VERSION" ]; then
      export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}";
    fi
  - |
    if [ -n "$CLANG_VERSION" ]; then
      export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}";
    fi
  - which $CXX
  - which $CC
  - which valgrind

script:
  - rm -rf build;
  - ./waf configure;
  - ./waf build --alltest --testcmd="valgrind -q --error-exitcode=1 %s";
