language: cpp
os: linux
compiler: gcc

before_install:
  - git log --name-status HEAD^..HEAD
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++;
  - export CXX="g++" CC="gcc";
  - sudo apt-get -qq install valgrind;

script:
  - rm -rf build;
  - ./waf configure --testcmd="valgrind -q --error-exitcode=1";
  - ./waf build;
