sudo: false
language: cpp
cache:
  - apt

matrix:
  include:
    - env: GCC_VERSION=4.9
      addons: &gcc49
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - valgrind

script:
  - rm -rf build;
  - CXX=g++-4.9 ./waf configure;
  - ./waf build;
